#pragma once

enum class FunctionType
{
	FOV_OVERRIDE,
	DISABLE_PLAYER_PERSPECTIVE,
	DISABLE_PLAYER_DIVE_MOSAIC,
	DISABLE_FOG,
	ENABLE_SET_FPS,
	REMOVE_TEAM_PROGRESS,
	HIDE_QUEST_BANNER,
	DISABLE_CAMERA_MOVE,
	DISABLE_DAMAGE_TEXT,
	TOUCH_MODE,
	RESIN_ITEM,
	DISPLAY_PAIMON,
	HIDE_PLAYER_INFO,
	HIDE_GRASS,
	GAMEPAD_HOT_SWITCH,
	IN_LEVEL_CLOCK_PAGE_SPEED_UP,
	COMBINE_HOTKEY,
	WEAK_MAP_CHECK,
};